export const URL_NAME = {
  FEED: "Feed",
  MESSAGES: "Message",
  CONNECTIONS: "Connections",
  DISCOVER: "Discover",
  PROFILE: "Profile",
  CHATBOT: "Chatbot",
  CREATE_POST: "Create post",
  AUTH: "Auth",
  SIGN_IN: "Sign in",
  SIGN_UP: "Sign up",
  FORGOT_PASSWORD: "Forgot password",
  RESET_PASSWORD: "Reset password",
  ADMIN: "Admin",
  ADMIN_POSTS_MANAGEMENT: "Posts Management",
};
